project:
  type: website
  output-dir: docs
  
website:
  title: "dashboards"
  navbar:
    right:
      - href: penguin.qmd
        text: Home
      
format:
  html:
    theme: 
      - green
      - brand
    css: styles.css
    toc: true

editor: visual

